# Generated by Django 2.2.11 on 2020-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200331_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='new',
            field=models.ManyToManyField(blank=True, related_name='homepage_new', to='home.CustomText'),
        ),
    ]
